In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn

In [4]:
df=pd.read_csv("C:\\Users\\user\\Downloads\\archive (1)\\UCI_Credit_Card.csv")
df

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000.0,1,3,1,39,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,29997,150000.0,1,3,2,43,-1,-1,-1,-1,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,29998,30000.0,1,2,2,37,4,3,2,-1,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,29999,80000.0,1,3,1,41,1,-1,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,30000,50000.0,1,2,1,46,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

In [5]:
df.info

<bound method DataFrame.info of           ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0          1    20000.0    2          2         1   24      2      2     -1
1          2   120000.0    2          2         2   26     -1      2      0
2          3    90000.0    2          2         2   34      0      0      0
3          4    50000.0    2          2         1   37      0      0      0
4          5    50000.0    1          2         1   57     -1      0     -1
...      ...        ...  ...        ...       ...  ...    ...    ...    ...
29995  29996   220000.0    1          3         1   39      0      0      0
29996  29997   150000.0    1          3         2   43     -1     -1     -1
29997  29998    30000.0    1          2         2   37      4      3      2
29998  29999    80000.0    1          3         1   41      1     -1      0
29999  30000    50000.0    1          2         1   46      0      0      0

       PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0         -1  ...        0.0        0.0        0.0       0.0     689.0
1          0  ...     3272.0     3455.0     3261.0       0.0    1000.0
2          0  ...    14331.0    14948.0    15549.0    1518.0    1500.0
3          0  ...    28314.0    28959.0    29547.0    2000.0    2019.0
4          0  ...    20940.0    19146.0    19131.0    2000.0   36681.0
...      ...  ...        ...        ...        ...       ...       ...
29995      0  ...    88004.0    31237.0    15980.0    8500.0   20000.0
29996     -1  ...     8979.0     5190.0        0.0    1837.0    3526.0
29997     -1  ...    20878.0    20582.0    19357.0       0.0       0.0
29998      0  ...    52774.0    11855.0    48944.0   85900.0    3409.0
29999      0  ...    36535.0    32428.0    15313.0    2078.0    1800.0

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default.payment.next.month
0           0.0       0.0       0.0       0.0                           1
1        1000.0    1000.0       0.0    2000.0                           1
2        1000.0    1000.0    1000.0    5000.0                           0
3        1200.0    1100.0    1069.0    1000.0                           0
4       10000.0    9000.0     689.0     679.0                           0
...         ...       ...       ...       ...                         ...
29995    5003.0    3047.0    5000.0    1000.0                           0
29996    8998.0     129.0       0.0       0.0                           0
29997   22000.0    4200.0    2000.0    3100.0                           1
29998    1178.0    1926.0   52964.0    1804.0                           1
29999    1430.0    1000.0    1000.0    1000.0                           1

[30000 rows x 25 columns]>

In [8]:
df.shape

(30000, 25)

In [11]:
df.isnull().sum()

ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default.payment.next.month    0
dtype: int64

In [16]:
x=df.drop(['default.payment.next.month'],axis=1)
x

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,689.0,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0
1,2,120000.0,2,2,2,26,-1,2,0,0,...,2682.0,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0
2,3,90000.0,2,2,2,34,0,0,0,0,...,13559.0,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0
3,4,50000.0,2,2,1,37,0,0,0,0,...,49291.0,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,35835.0,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000.0,1,3,1,39,0,0,0,0,...,208365.0,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0
29996,29997,150000.0,1,3,2,43,-1,-1,-1,-1,...,3502.0,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0
29997,29998,30000.0,1,2,2,37,4,3,2,-1,...,2758.0,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0
29998,29999,80000.0,1,3,1,41,1,-1,0,0,...,76304.0,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0
29999,30000,50000.0,1,2,1,46,0,0,0,0,...,49764.0,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0

In [18]:
y=df['default.payment.next.month']
y

0        1
1        1
2        0
3        0
4        0
        ..
29995    0
29996    0
29997    1
29998    1
29999    1
Name: default.payment.next.month, Length: 30000, dtype: int64

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)
x_train

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
21177,21178,300000.0,1,3,2,31,0,0,0,0,...,84462.0,86263.0,87238.0,89176.0,4000.0,4000.0,4100.0,3300.0,3500.0,3500.0
23942,23943,20000.0,1,2,2,24,0,0,0,0,...,35036.0,14694.0,16914.0,14074.0,1313.0,2110.0,4000.0,6000.0,4000.0,174.0
1247,1248,90000.0,2,2,2,35,-1,-1,-1,-2,...,0.0,0.0,0.0,0.0,2667.0,0.0,0.0,0.0,0.0,0.0
23622,23623,300000.0,2,2,1,40,1,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28454,28455,70000.0,2,2,2,36,0,0,0,0,...,59165.0,29314.0,28844.0,29443.0,3340.0,2044.0,1773.0,1181.0,1215.0,1297.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29802,29803,50000.0,1,2,2,32,0,0,0,0,...,55739.0,55957.0,29238.0,6119.0,2000.0,3000.0,1591.0,72.0,1134.0,73421.0
5390,5391,200000.0,1,1,2,37,2,2,2,2,...,168386.0,164182.0,169029.0,172084.0,13500.0,6000.0,0.0,7500.0,6000.0,4000.0
860,861,50000.0,1,1,2,26,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15795,15796,70000.0,2,2,2,25,0,0,0,0,...,51152.0,35122.0,28633.0,28039.0,3000.0,2000.0,4500.0,1200.0,0.0,1200.0
23654,23655,160000.0,2,2,1,36,-2,-2,-2,-2,...,3640.0,2935.0,1603.0,14129.0,0.0,3660.0,3135.0,1650.0,14200.0,1500.0

In [23]:
x_test

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
2308,2309,30000.0,1,2,2,25,0,0,0,0,...,11581.0,12580.0,13716.0,14828.0,1500.0,2000.0,1500.0,1500.0,1500.0,2000.0
22404,22405,150000.0,2,1,2,26,0,0,0,0,...,116684.0,101581.0,77741.0,77264.0,4486.0,4235.0,3161.0,2647.0,2669.0,2669.0
23397,23398,70000.0,2,3,1,32,0,0,0,0,...,68530.0,69753.0,70111.0,70212.0,2431.0,3112.0,3000.0,2438.0,2500.0,2554.0
25058,25059,130000.0,1,3,2,49,0,0,0,0,...,16172.0,16898.0,11236.0,6944.0,1610.0,1808.0,7014.0,27.0,7011.0,4408.0
2664,2665,50000.0,2,2,2,36,0,0,0,0,...,42361.0,19574.0,20295.0,19439.0,2000.0,1500.0,1000.0,1800.0,0.0,1000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3211,3212,40000.0,2,3,1,49,1,-2,-2,-2,...,0.0,0.0,0.0,150.0,0.0,0.0,0.0,0.0,150.0,159.0
9355,9356,330000.0,2,2,1,42,0,0,0,0,...,32912.0,36710.0,40442.0,42283.0,10000.0,10000.0,5000.0,5000.0,5000.0,5000.0
28201,28202,300000.0,2,3,2,48,1,3,2,-1,...,390.0,769.0,772.0,1722.0,781.0,1.0,769.0,3.0,1730.0,0.0
19705,19706,100000.0,2,2,1,47,-1,-1,-1,-1,...,0.0,6270.0,-396.0,-396.0,6666.0,0.0,6270.0,0.0,0.0,0.0
28313,28314,120000.0,2,3,1,34,-2,-1,-1,-1,...,389.0,978.0,0.0,2358.0,360.0,389.0,978.0,0.0,2358.0,0.0

In [35]:
model=SVC()

In [36]:
model.fit(x_train,y_train)

SVC()

In [37]:
model.score(x_test,y_test)

0.7830666666666667

In [38]:
predict_y=model.predict(x_test)

In [39]:
print(predict_y)

[0 0 0 ... 0 0 0]

In [42]:
from sklearn.ensemble import RandomForestClassifier
m=RandomForestClassifier()
m.fit(x_train,y_train)
m.score(x_test,y_test)

0.8150666666666667

In [43]:
from sklearn.tree import DecisionTreeClassifier
model1=DecisionTreeClassifier()
model1.fit(x_train,y_train)
model1.score(x_test,y_test)

0.7298666666666667